### ISSUE TITLE
Getting error while registration

### ISSUE THREAD

**Issue by avighub** [pvishnuprasaath/react-social-v1#1]
- Error title : Unexpected Application Error!
- Steps:
  - register for new user

log:
`Error: Objects are not valid as a React child (found: object with keys {code, fatal}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/static/js/bundle.js:45790:13)
    at updateSlot (http://localhost:3000/static/js/bundle.js:46105:11)
    at reconcileChildrenArray (http://localhost:3000/static/js/bundle.js:46251:26)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:46720:20)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:50904:32)
    at updateHostComponent$1 (http://localhost:3000/static/js/bundle.js:51611:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:53269:18)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:58055:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:57253:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:57167:9)`

**Comment by neurogreedy** [comment]
did u solved it? i got the same

**Comment by avighub** [comment]
> did u solved it? i got the same

No, I moved on to something else, did not spend time
